apiVersion: apps/v1
kind: Deployment
metadata:
  name: memeservices
  labels:
    name: memeservices
spec:
  replicas: 4
  selector:
    matchLabels:
      app: memeservices
  template:
    metadata:
      labels:
        app: memeservices
    spec:
      containers:
      - name: memeservices
        image: ramseymcgrath/memeservicesapp:latest
        ports:
        - containerPort: 8081

---

kind: Service
apiVersion: v1
metadata:
  name: memeservices-service
spec:
  selector:
    app: memeservices
  ports:
  - protocol: TCP
    port: 8443

---

kind: Service
apiVersion: v1
metadata:
  name: unforgivable-service
spec:
  selector:
    app: memeservices
  ports:
  - protocol: TCP
    port: 8444

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: memeservices-hpa
  annotations:
    name: memeservices
    namespace: memeservices
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1
    kind: Deployment
    name: memeservices-deployment-scaler
  targetCPUUtilizationPercentage: 1

---

kind: Ingress
apiVersion: networking.k8s.io/v1beta1
metadata:
  name: memeservices-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /memeservices
        backend:
          serviceName: memeservices-service
          servicePort: 8443
      - path: /unforgivable
        backend:
          serviceName: unforgivable-service
          servicePort: 8444
      - http:
        backend:
          serviceName: memeservices-service
          servicePort: 8443